# Generated by Django 2.1.7 on 2019-04-19 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='flight name')),
                ('origin', models.CharField(max_length=50, verbose_name='flight origin')),
                ('destination', models.CharField(max_length=50, verbose_name='flight destination')),
                ('date_of_travel', models.DateTimeField(verbose_name='Date And Time of Travel')),
                ('capacity', models.IntegerField(verbose_name='Number of passengers the flight can accommodate.')),
                ('reservations_available', models.IntegerField(verbose_name='Number of reservations left for the flight')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('landed', 'Landed')], default='scheduled', max_length=150)),
            ],
        ),
    ]
