# Generated by Django 2.1.7 on 2019-04-14 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50, verbose_name='passenger origin')),
                ('destination', models.CharField(max_length=50, verbose_name='passenger destination')),
                ('date_of_travel', models.DateField(verbose_name='Date of Travel')),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('late', 'Late'), ('done', 'Done')], default='active', max_length=150)),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='flight.Flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
