# Generated by Django 2.1.7 on 2019-04-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('not_paid', 'Not Paid')], default='not_paid', max_length=10)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='flight.Reservation')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Cost for the Flight.'),
        ),
    ]
