# Generated by Django 2.1.7 on 2019-03-11 11:16

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightuser',
            name='passport_photo',
            field=models.ImageField(blank=True, upload_to=authentication.models.user_passport, verbose_name='Passport Photo'),
        ),
    ]
